name: GitHub Actions Deploy CI
on:
  push:
    branches:
      - main
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to ACR
      uses: aliyun/acr-login@v1
      with:
        login-server: https://registry.cn-hangzhou.aliyuncs.com
        access-key-id: "${{ secrets.ALIYUN_REGISTRY_USERNAME }}"
        access-key-secret: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"
    - name: Build and push image
      env:
        IMAGE_TAG: latest # ${{ github.sha }}
      run: |
        docker build -t registry.cn-hangzhou.aliyuncs.com/ncj/msaas:$IMAGE_TAG .
        docker push registry.cn-hangzhou.aliyuncs.com/ncj/msaas:$IMAGE_TAG