name: GitHub Actions Test and Build CI
on:
  push:
    branches:
      - main
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        check-latest: true
    - run: yarn install
    - run: yarn test
    - run: yarn build