name: Deploy
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and push image
      env:
        IMAGE_TAG: latest # ${{ github.sha }}
      run: |
        docker login --username=${{ secrets.ALIYUN_REGISTRY_USERNAME }} --password=${{ secrets.ALIYUN_REGISTRY_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
        docker build -t registry.cn-hangzhou.aliyuncs.com/ncj/msaas:$IMAGE_TAG .
        docker push registry.cn-hangzhou.aliyuncs.com/ncj/msaas:$IMAGE_TAG
